{% set name = "torchtime" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torchtime-{{ version }}.tar.gz
  sha256: 9b23ffbb063e8ec147d3aa8468eb839eb68839c4123510396d40ee93fda9fce3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.8,<3.10
    - pip
    - poetry >=1
  run:
    - python >=3.8,<3.10
    - sktime >=0.12.1,<0.13
    - requests >=2.27.1,<3
    - scikit-learn >=1.1.1,<2
    - tqdm >=4.64.0,<5
    - pytorch >=1.11.0,<2
    - numpy >=1.21.0,<2

test:
  imports:
    - torchtime
    - torchtime.collate
    - torchtime.constants
    - torchtime.data
    - torchtime.utils
  commands:
    - pip check
  requires:
    # FIXME: Skip broken sktime builds. Remove for next sktime release.
    # There is no sktime=0.12.2
    - sktime =0.12.1=*2
    - pip

about:
  home: https://philipdarke.com/torchtime
  dev_url: https://github.com/philipdarke/torchtime
  summary: Benchmark time series data sets for PyTorch
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - philipdarke
